### ISSUE TITLE
image and pass

### ISSUE THREAD

**Issue by xiefg** [dukn/Captcha-recognition-TF#1]
Listing examples of pictures and pass files in directory Captcha

**Comment by ChoudharyDiksha** [comment]
I am trying to run training_captcha.py code and getting below error: 
File "training_captcha.py", line 190, in <module>
    new_saver = tf.train.import_meta_graph('train2.data.meta')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1803, in import_meta_graph
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 555, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
IOError: File train2.data.meta does not exist.

Any help would be appreciated regarding the execution of this whole project, thanks in advance.
My email address is: diksha260@gmail.com

**Comment by ghost** [comment]
I have the same problem as Diksha260. Where is this file? how do we generate it? please respond.

**Comment by dukn** [comment]
@Diksha260 , @morkia , 
Please comment lines 187, 188, 189 and uncomment line 191.
Ex:
```
	#new_saver = tf.train.import_meta_graph('train2.data.meta')
	#new_saver.restore(sess, tf.train.latest_checkpoint('./'))
	#all_vars = tf.trainable_variables()

	sess.run(init)
```
But this source code conflicts with Tensorflow, I'm building a new source code and will update soon.
Thank you!

**Comment by dukn** [comment]
@xiefg  @Diksha260 @morkia The new version have been updated here 
https://github.com/dukn/Captcha-recognition-Keras

**Comment by ghost** [comment]
Thank you for your quick response. This solved the issue.
